/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.pratclot.orderly

import org.gradle.internal.impldep.org.junit.Ignore
import org.junit.jupiter.api.BeforeEach
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.pratclot.orderly' plugin.
 */
class OrderlyPluginTest : BaseTest() {


    @BeforeEach
    fun setup() {
        before()
    }

    @Ignore
    @Test
    fun `plugin registers task`() {


        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
